name: relearn

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: make check
      run: gcc main.c Addition.c -o Addition.out
    - name: make distcheck
      run: make distcheck
